#! /bin/sh
# /etc/init.d/logSystem_daemon

#
### BEGIN INIT INFO
#Provides:          logSystem_daemon
#Processname:       logSystem_daemon
#Required-Start:    $network
#Required-Stop:     $network
#Default-Start:     S 2 
#Default-Stop:      0 1 6
#Short-Description: Flask , Router web interface 
#Description:       Flask is an open source, A micro python web framework.
#                    http://flask.com
### END INIT INFO

#exec 1>/tmp/logSystem_daemon.log 2>&1

case "$1" in
  start)
    echo "Starting logSystem Daemon"
    # run application you want to start
    /www/monitor_system/SysInfo.sh &
    ;;
  stop)
    echo "Stopping logSystem Daemon"
    # kill application you want to stop
    kill $(ps aux | grep "/www/monitor_system/SysInfo.sh" | grep -v grep | awk '{print $2}') 
    ;;
  restart)
    echo "Restarting the ilogSystem Daemon"
    kill $(ps aux | grep "/www/monitor_system/SysInfo.sh" | grep -v grep | awk '{print $2}') &
    /www/monitor_system/SysInfo.sh &
    ;;
  *)
    echo "Usage: /etc/init.d/logSystem_daemon  {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
