#! /bin/sh
# /etc/init.d/reboot_daemon

#
### BEGIN INIT INFO
# Provides:          reboot_daemon
# Processname:       reboot_daemon
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     S 2
# Default-Stop:      0 1 6
# Short-Description: Flask , Router web interface 
# Description:       Flask is an open source, A micro python web framework.
#                    http://flask.com
### END INIT INFO
#exec 1>/tmp/reboot_daemon.log 2>&1

case "$1" in
  start)
    echo "Starting reboot daemon"
    # run application you want to start
    python3 /www/web/_netw/reboot.py > /var/log/reboot_daemon.log &
    ;;
  stop)
    echo "Stopping reboot_daemon"
    # kill application you want to stop
    kill $(ps aux | grep "python3 /www/web/reboot_Main.py" | grep -v grep | awk '{print $2}')
    ;;
  *)
    echo "Usage: /etc/init.d/reboot_daemon{start|stop}"
    exit 1
    ;;
esac

exit 0
