#! /bin/sh
# /etc/init.d/sendTempDist_daemon

#
### BEGIN INIT INFO
# Provides:          sendTempDist_daemon 
# Processname:       sendTempDist_daemon
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     S 2 
# Default-Stop:      0 1 6
# Short-Description: Flask , Router web interface 
# Description:       Flask is an open source, A micro python web framework.
#                    http://flask.com
### END INIT INFO

#exec 1>/tmp/sendTempDist_daemon.log 2>&1




case "$1" in
  start)
    echo "Starting sendTempDist_daemon Daemon"
    # run application you want to start
    python3 /www/web/_netw/sendTempDist.py &
    ;;
  stop)
    echo "Stopping sendTempDist_daemon Daemon"
    # kill application you want to stop
    kill $(ps aux | grep "python3 /www/web/_netw/sendTempDist.py" | grep -v grep | awk '{print $2}') 
    ;;
  restart)
    echo "Restarting the sendTempDist_daemon Daemon"
    kill $(ps aux | grep "python3 /www/web/_netw/sendTempDist.py" | grep -v grep | awk '{print $2}') &
    python3 /www/web/_netw/sendTempDist.py &
    ;;
  *)
    echo "Usage: /etc/init.d/sendTempDist_daemon  {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
